namespaceOverride: "keycloak-system"

image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 24.0.5-debian-12-r1
  debug: false

auth:
  adminUser: choigonyok
  adminPassword: <path:home-k8s/data/keycloak/admin#password>
  existingSecret: ""
  passwordSecretKey: ""
  annotations: {}

## ref: https://www.keycloak.org/server/keycloak-truststore
spi:
  existingSecret: ""
  truststorePassword: ""
  truststoreFilename: "keycloak-spi.truststore.jks"
  passwordsSecret: ""
  hostnameVerificationPolicy: ""

production: true

## ref: https://www.keycloak.org/server/reverseproxy
proxy: edge # or reencrypt, passthrough

replicaCount: 3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1024Mi

nodeAffinityPreset:
  type: "soft" # or hard
  key: "node-type"
  values:
    - worker

podAntiAffinityPreset: soft

adminIngress:
  enabled: true
  ingressClassName: "nginx"
  pathType: Prefix
  hostname: auth.choigonyok.com
  path: "/"
  servicePort: http
  annotations: {}

networkPolicy:
  enabled: false

postgresql:
  enabled: false

externalDatabase:
  host: "keycloak-pg.postgres-system.svc.cluster.local"
  port: 5432
  user: keycloak
  database: keycloak_db
  password: <path:home-k8s/data/postgres/keycloak#password>
  existingSecret: ""
  existingSecretHostKey: ""
  existingSecretPortKey: ""
  existingSecretUserKey: ""
  existingSecretDatabaseKey: ""
  existingSecretPasswordKey: ""
  annotations: {}

## ref: https://www.keycloak.org/server/caching
cache:
  enabled: true
  stackName: kubernetes
  stackFile: ""

logging:
  output: default
  level: INFO