apiVersion: v1
kind: Service
metadata:
  name: techlog
  namespace: dev-system
spec:
  selector:
    app: techlog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: techlog-ui
  namespace: dev-system
spec:
  selector:
    app: techlog-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

# <path