apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlog
  namespace: dev-system
  labels:
    app: techlog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techlog
  template:
    metadata:
      labels:
        app: techlog
    spec:
      containers:
      - name: techlog
        image: achoistic98/techlog:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: techlog-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techlog-ui
  namespace: dev-system
  labels:
    app: techlog-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techlog-ui
  template:
    metadata:
      labels:
        app: techlog-ui
    spec:
      containers:
      - name: techlog-ui
        image: achoistic98/techlog-ui:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: techlog-ui-env
---
apiVersion: v1
kind: Secret
metadata:
  name: techlog-env
  namespace: dev-system
type: Opaque
stringData:
  HOME_IDP_GIT_OAUTH_CLIENT_ID: <path:kv/data/techlog#HOME_IDP_GIT_OAUTH_CLIENT_ID>
  HOME_IDP_GIT_OAUTH_CLIENT_SECRET: <path:kv/data/techlog#HOME_IDP_GIT_OAUTH_CLIENT_SECRET>
  OAUTH_RANDOM_STRING: <path:kv/data/techlog#OAUTH_RANDOM_STRING>
  JWT_RANDOM_STRING: <path:kv/data/techlog#JWT_RANDOM_STRING>
  AWS_ACCESS_KEY: <path:kv/data/techlog#AWS_ACCESS_KEY>
  AWS_SECRET_KEY: <path:kv/data/techlog#AWS_SECRET_KEY>
---
apiVersion: v1
kind: Secret
metadata:
  name: techlog-ui-env
  namespace: dev-system
type: Opaque
stringData:
  REACT_APP_HOST: techlog:8080
---
apiVersion: v1
kind: Service
metadata:
  name: techlog
  namespace: dev-system
spec:
  selector:
    app: techlog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: techlog-ui
  namespace: dev-system
spec:
  selector:
    app: techlog-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000