apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  namespace: argocd-system
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/choigonyok/home-k8s.git
      path: test/nginx
      targetRevision: HEAD
      plugin:
        name: argocd-vault-plugin-helm
    - repoURL: https://github.com/choigonyok/home-k8s.git
      path: test/nginx
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true