# SecretStore는 외부 Vault 서버의 특정 경로에 저장된 시크릿들과, ExternalSecret을 연결해주는 컴포넌트입니다.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-vault-backend
  namespace: minio-system
spec:
  provider:
    vault:
      server: "http://vault-internal.vault-system.svc.cluster.local:8200" # 수정, External Vault Server Host
      path: "home-k8s"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "minio-vault-token"
          key: "token"
---
# 외부 Vault 서버와 연결하기 위해 Vault Authn Token을 제공하는 오브젝트입니다.
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-vault-token
  namespace: minio-system
data:
  token: <path:vault/tokens/keycloak> # Vault Root Token을 base64 인코딩한 값, echo -n으로 출력해야함.
---
# ExternalSecret은 SecretStore를 통해 Vault 시크릿들을 가져와서 K8s에 Secret 오브젝트로 저장하는 역할을 합니다.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-secret-keycloak
  namespace: vault-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: keycloak-vault-backend
    kind: SecretStore
  target:
    name: keycloak-vault-secret
  data:
  - secretKey: postgres-password # K8s에 저장될 시크릿의 키
    remoteRef:
      key: keycloak/db # SecretEngine의 SubPath 
      property: password  # Vault에 저장된 시크릿의 키
  - secretKey: keycloak-user
    remoteRef:
      key: keycloak/admin
      property: username
  - secretKey: keycloak-password
    remoteRef:
      key: keycloak/admin
      property: password