apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-idp
subjects:
- kind: ServiceAccount
  name: home-idp-install-manager
  namespace: {{ .Values.global.namespace | quote }}
- kind: ServiceAccount
  name: home-idp-deploy-manager
  namespace: {{ .Values.global.namespace | quote }}
- kind: ServiceAccount
  name: home-idp-gateway
  namespace: {{ .Values.global.namespace | quote }}
- kind: ServiceAccount
  name: home-idp-ui
  namespace: {{ .Values.global.namespace | quote }}
- kind: ServiceAccount
  name: home-idp-rbac-manager
  namespace: {{ .Values.global.namespace | quote }}
- kind: ServiceAccount
  name: home-idp-trace-manager
  namespace: {{ .Values.global.namespace | quote }}
roleRef:
  kind: ClusterRole
  name: home-idp
  apiGroup: rbac.authorization.k8s.io


