apiVersion: v1
kind: ConfigMap
metadata:
  name: home-idp-cm
  namespace: {{ .Values.global.namespace }}
data:
  config.yaml: |
    global:
      namespace: {{ .Values.global.namespace }}
      port: 5103
      ingress:
        host: {{ .Values.ingress.gateway.host }}
        port: {{ .Values.ingress.gateway.port }}
        tls: {{ .Values.ingress.gateway.tls }}
      git:
        username: {{ .Values.git.username }}
        email : {{ .Values.git.email }}
        token: {{ .Values.git.repository.token }}
        repository: {{ .Values.git.repository.name }}
        oauth:
          clientId: {{ .Values.git.oauth.clientId }}
          clientSecret: {{ .Values.git.oauth.clientSecret }}

      adminPassword: {{ .Values.auth.adminPassword }}

      harbor:
        host: {{ .Values.ingress.harbor.host }}
        port: {{ .Values.ingress.harbor.port }}
        tls: {{ .Values.ingress.harbor.tls }}
      ui:
        host: {{ .Values.ingress.ui.host }}
        port: {{ .Values.ingress.ui.port }}
        tls: {{ .Values.ingress.ui.tls }}

    gateway:
      service:
        port: 5106
        type: ClusterIP

    storage:
      username: {{ .Values.storage.database.username }}
      password: {{ .Values.storage.database.password }}
      database: {{ .Values.storage.database.name }}
      persistence:
        storageClass: {{ .Values.storage.persistence.storageClass }}
        size: {{ .Values.storage.persistence.size }}