replicaCount: 3

image:
  tag: v1.11.0

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

envs:
  appUrl: http://postgres-operator-ui:8081
  operatorApiUrl: http://postgres-operator:8080
  operatorClusterNameLabel: "cluster-name"
  resourcesVisible: "True"
  targetNamespace: "*"
  teams:
    - "choigonyok"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://proxy.choigonyok.com/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://proxy.choigonyok.com/oauth2/auth
  ingressClassName: "nginx"
  hosts:
    - host: postgres.choigonyok.com
      paths: ["/"]

nodeSelector:
  node-type: worker