apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: techlog-pg
  namespace: postgres-system
spec:
  teamId: choigonyok
  volume:
    size: 30G
    storageClass: ceph-block
  numberOfInstances: 3
  users:
    choigonyok:
    - superuser
  databases:
    techlog_db: choigonyok
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  postgresql:
    version: "16"
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 500Mi
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - worker
  patroni:
    failsafe_mode: false
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
      - hostssl all all 0.0.0.0/0 md5
      - host    all all 0.0.0.0/0 md5
      - hostnossl all all 0.0.0.0/0 md5
      - local all all 0.0.0.0/0 md5