apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-redis
  namespace: argocd-system
spec:
  destination:
    name: ''
    namespace: redis-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: redis/application/apps
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true