deploymentMode: Distributed

loki:
  auth_enabled: false

  schemaConfig:
    configs:
      - from: 2020-07-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

  ingester:
    chunk_encoding: snappy
    
  tracing:
    enabled: true

  querier:
    max_concurrent: 4

  distributor:
    otlp_config:
      default_resource_attributes_as_index_labels: 
        - service.name
        - service.namespace
        - service.instance.id
        - deployment.environment
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.container.name
        - k8s.replicaset.name
        - k8s.deployment.name
        - k8s.statefulset.name 
        - k8s.daemonset.name
        - k8s.cronjob.name
        - event.domain
        - event.name
        - k8s.job.name

  compactor:
    working_directory: /loki/retention
    compaction_interval: 10m
    retention_enabled: true 
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3
  limits_config:
    retention_period: 24h
    allow_structured_metadata: true

    otlp_config:
      resource_attributes:
        ignore_defaults: false

  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      s3: http://app-minio-svc.minio-system.svc.cluster.local:9000
      endpoint:
      region: ap-northeast-2
      accessKeyId: <path:home-k8s/data/minio/users/root#username>
      secretAccessKey: <path:home-k8s/data/minio/users/root#password>
      s3ForcePathStyle: true
      insecure: true
      http_config: {}
  storage_config:
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      cache_ttl: 24h

compactor:
  replicas: 1
  affinity: {}
  nodeSelector:
    node-type: worker
  extraVolumes:
    - name: retention
      emptyDir: {}
  extraVolumeMounts:
    - name: retention
      mountPath: /loki/retention

distributor:
  replicas: 3
  affinity: null
  nodeSelector:
    node-type: worker
  maxUnavailable: 2

indexGateway:
  replicas: 2
  affinity: {}
  nodeSelector:
    node-type: worker
  maxUnavailable: 1
  extraVolumes:
    - name: cache
      emptyDir: {}
  extraVolumeMounts:
    - name: cache
      mountPath: /loki/index_cache

ingester:
  replicas: 3
  affinity: {}
  nodeSelector:
    node-type: worker
  zoneAwareReplication:
    zoneA:
      nodeSelector:
        node-number: one
    zoneB:
      nodeSelector:
        node-number: two
    zoneC:
      nodeSelector:
        node-number: three
  extraVolumes:
    - name: index
      emptyDir: {}
  extraVolumeMounts:
    - name: index
      mountPath: /loki/index

querier:
  replicas: 3
  affinity: null
  nodeSelector:
    node-type: worker
  maxUnavailable: 2

queryFrontend:
  replicas: 2
  affinity: {}
  nodeSelector:
    node-type: worker
  maxUnavailable: 1

queryScheduler:
  replicas: 2
  affinity: {}
  nodeSelector:
    node-type: worker

bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

minio:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0 