expose:
  tls:
    enabled: false
  ingress:
    hosts:
      core: registry.choigonyok.com
    className: "nginx"

externalURL: https://registry.choigonyok.com

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    jobservice:
      jobLog:
        existingClaim: ""
        storageClass: "ceph-block"
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
        annotations: {}
    trivy:
      existingClaim: ""
      storageClass: "ceph-block"
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
      annotations: {}
  imageChartStorage:
    disableredirect: true
    type: s3
    s3:
      region: ap-northeast-2
      bucket: registry
      accesskey: harbor
      secretkey: <path:kv/data/minio#HARBOR_SECRET_KEY>
      regionendpoint: http://app-minio-svc.minio-system.svc.cluster.local:9000

harborAdminPassword: <path:kv/data/harbor#ADMIN_PASSWORD>

database:
  type: external
  external:
    host: "harbor-pg.postgres-system.svc.cluster.local"
    port: "5432"
    username: "harbor"
    password: <path:kv/data/postgres#HARBOR_PASSWORD>
    coreDatabase: "harbor_db"
    sslmode: "require"
  maxIdleConns: 100
  maxOpenConns: 900
  podAnnotations: {}
  podLabels: {}

redis:
  type: external
  external:
    addr: "redis-harbor-headless.redis-system.svc.cluster.local:26379"
    sentinelMasterSet: "harbor-master"
    coreDatabaseIndex: "0"
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
    harborDatabaseIndex: "6"
    cacheLayerDatabaseIndex: "7"
    username: "default"
    password: <path:kv/data/redis#ROOT_PASSWORD>
    existingSecret: ""
  podAnnotations: {}
  podLabels: {}

exporter:
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: exporter
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: exporter

nginx:
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: nginx
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: nginx

portal:
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: portal
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: portal

core:
  image:
    repository: goharbor/harbor-core
    tag: v2.5.1
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: core
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: core

jobservice:
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: jobservice
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: jobservice

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.5.3
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: registry
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: registry

trivy:
  replicas: 3
  nodeSelector:
    node-type: worker
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              harbor: trivy
          topologyKey: kubernetes.io/hostname
  podLabels:
    harbor: trivy