global:
  redis:
    password: <path:kv/data/redis#ROOT_PASSWORD>
  storageClass: "ceph-block"

nameOverride: "redis-harbor"
fullnameOverride: "redis-harbor"
namespaceOverride: "redis-system"

replica:
  replicaCount: 3
  nodeSelector:
    node-type: worker
  podAffinityPreset: "soft"
  resourcesPreset: "small"

sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: 7.2.5-debian-12-r0
    digest: ""
    debug: false
  resourcesPreset: "small"
  masterSet: "harbor-master"

volumePermissions:
  enabled: true

auth:
  enabled: false
  sentinel: false