image:
  repository: quay.io/minio/minio
  tag: latest
  pullPolicy: IfNotPresent

mode: distributed

priorityClassName: ""
runtimeClassName: ""
rootUser: <path:kv/data/minio#rootUser>
rootPassword: <path:kv/data/minio#rootPassword>

certsPath: "/etc/minio/certs/"
configPathmc: "/etc/minio/mc/"

mountPath: "/export"
bucketRoot: ""

drivesPerNode: 1
replicas: 4
pools: 1

tls:
  enabled: false
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key

trustedCertsSecret: ""

persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  storageClass: "ceph-block"
  volumeName: ""
  accessMode: ReadWriteOnce
  size: 150Gi
  subPath: ""

ingress:
  enabled: false

consoleIngress:
  enabled: true
  ingressClassName: nginx
  labels: {}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.org/websocket-services: "app-minio-console"
  path: /
  hosts:
    - s3.choigonyok.com
  tls: []

nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: minio
        topologyKey: kubernetes.io/hostname
topologySpreadConstraints: []

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
  readOnlyRootFilesystem: false

podAnnotations: {}

podLabels:
  app: minio

resources:
  requests:
    memory: 2Gi

policies:
- name: admin-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::*'
      actions:
        - "s3:*"
- name: viewer-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::*'
      actions:
        - 's3:Get*'
        - 's3:List*'
- name: harbor-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::registry/*'
      actions:
        - 's3:*'
- name: loki-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::loki*/*'
      actions:
        - 's3:*'
- name: mimir-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::mimir*/*'
      actions:
        - 's3:*'
- name: tempo-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::tempo*/*'
      actions:
        - 's3:*'
- name: velero-policy
  statements:
    - effect: Allow 
      resources:
        - 'arn:aws:s3:::postgresql/*'
        - 'arn:aws:s3:::vault/*'
        - 'arn:aws:s3:::redis/*'
      actions:
        - 's3:*'

            
users:
  - accessKey: viewer
    secretKey: viewer123
    policy: viewer-policy
  - accessKey: harbor
    secretKey: <path:kv/data/minio#HARBOR_SECRET_KEY>
    policy: harbor-policy
  - accessKey: loki
    secretKey: <path:kv/data/minio#LOKI_SECRET_KEY>
    policy: loki-policy
  - accessKey: mimir
    secretKey: <path:kv/data/minio#MIMIR_SECRET_KEY>
    policy: mimir-policy
  - accessKey: tempo
    secretKey: <path:kv/data/minio#TEMPO_SECRET_KEY>
    policy: tempo-policy
  - accessKey: velero
    secretKey: <path:kv/data/minio#VELERO_SECRET_KEY>
    policy: velero-policy
  # - accessKey: loki
  #   secretKey: <path:home-k8s/data/minio/users/loki#password>
  #   policy: consoleAdmin

svcaccts: []

buckets:
  - name:  registry
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  mimir-alertmanager
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  mimir-ruler
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  mimir-blocks
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  postgresql
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  vault
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  redis
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  loki-chunks
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  loki-ruler
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  loki-admin
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  tempo-traces
    policy: none
    purge: false
    versioning: true
    objectlocking: false

environment:

oidc:
  enabled: true
  configUrl: "https://auth.choigonyok.com/realms/home-k8s/.well-known/openid-configuration"
  clientId: "minio-client"
  clientSecret: ""
  existingClientSecretName: ""
  existingClientIdKey: ""
  existingClientSecretKey: ""
  claimName: "consoleAdmin"
  scopes: "openid,profile,email,roles"
  redirectUri: "https://s3.choigonyok.com/oauth_callback"
  claimPrefix: "roles"
  comment: "test"
  displayName: "Login with Keycloak"

networkPolicy:
  enabled: false

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

serviceAccount:
  create: true
  name: "minio-sa"

metrics:
  serviceMonitor:
    enabled: true
    includeNode: false
    public: true
    additionalLabels: {}
    annotations: {}
    relabelConfigs: {}
    relabelConfigsCluster: {}
    namespace: ~
    interval: ~
    scrapeTimeout: ~

etcd:
  endpoints: []
  pathPrefix: ""
  corednsPathPrefix: ""
  clientCert: ""
  clientCertKey: ""