nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local
image:
  repository: quay.io/minio/minio
  tag: RELEASE.2024-04-18T19-09-19Z
  pullPolicy: IfNotPresent

imagePullSecrets: []

mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2024-04-18T16-45-29Z
  pullPolicy: IfNotPresent

mode: distributed

additionalLabels: {}
additionalAnnotations: {}
ignoreChartChecksums: false
extraArgs: []

extraVolumes: []
extraVolumeMounts: []
extraContainers: []

minioAPIPort: "9000"
minioConsolePort: "9001"

deploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

statefulSetUpdate:
  updateStrategy: RollingUpdate

priorityClassName: ""
runtimeClassName: ""
rootUser: <path:home-k8s/data/minio/users/root#username>
rootPassword: <path:home-k8s/data/minio/users/root#password>

certsPath: "/etc/minio/certs/"
configPathmc: "/etc/minio/mc/"

mountPath: "/export"
bucketRoot: ""

drivesPerNode: 1
replicas: 4
pools: 1

tls:
  enabled: false
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key

trustedCertsSecret: ""

persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  storageClass: "ceph-block"
  volumeName: ""
  accessMode: ReadWriteOnce
  size: 250Gi

  subPath: ""

service:
  type: ClusterIP
  clusterIP: ~
  port: "9000"
  nodePort: 32000
  loadBalancerIP: ~
  externalIPs: []
  annotations: {}

  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster

ingress:
  enabled: false
  ingressClassName: ~
  labels: {}
  annotations: {}
  path: /
  hosts: []
  tls: []

consoleService:
  type: ClusterIP
  clusterIP: ~
  port: "9001"
  nodePort: 32001
  loadBalancerIP: ~
  externalIPs: []
  annotations: {}
  loadBalancerSourceRanges: []

  externalTrafficPolicy: Cluster

consoleIngress:
  enabled: true
  ingressClassName: cilium
  labels: {}
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
    ingress.cilium.io/service-type: ClusterIP
  path: /
  hosts:
    - s3.choigonyok.com
  tls: []

nodeSelector: {}
tolerations: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchLabels:
            app: minio
        topologyKey: kubernetes.io/hostname
topologySpreadConstraints: []

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
  readOnlyRootFilesystem: false

podAnnotations: {}
podLabels:
  app: minio
resources:
  requests:
    memory: 2Gi

policies: []

makePolicyJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

users:
  - accessKey: mimir
    secretKey: <path:home-k8s/data/minio/users/mimir#password>
    policy: consoleAdmin
  - accessKey: velero
    secretKey: <path:home-k8s/data/minio/users/velero#password>
    policy: consoleAdmin

makeUserJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

svcaccts:
  - accessKey: mimir-svcacct
    secretKey: <path:home-k8s/data/minio/svcaccts/mimir#password>
    user: mimir

makeServiceAccountJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

buckets:
  - name:  mimir-alertmanager
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  mimir-ruler
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  mimir-blocks
    policy: none
    purge: false
    versioning: true
    objectlocking: false
  - name:  postgresql
    policy: none
    purge: false
    versioning: true
    objectlocking: false

makeBucketJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

customCommands:
customCommandJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

postJob:
  podAnnotations: {}
  annotations: {}
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

environment:

oidc:
  enabled: false
  configUrl: "https://identity-provider-url/.well-known/openid-configuration"
  clientId: "minio"
  clientSecret: ""
  # Provide existing client secret from the Kubernetes Secret resource, existing secret will have priority over `clientId` and/or `clientSecret``
  existingClientSecretName: ""
  existingClientIdKey: ""
  existingClientSecretKey: ""
  claimName: "policy"
  scopes: "openid,profile,email"
  redirectUri: "https://console-endpoint-url/oauth_callback"
  claimPrefix: ""
  comment: ""
  displayName: ""

networkPolicy:
  enabled: false
  flavor: cilium
  allowExternal: true
  egressEntities:
   - kube-apiserver

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1

serviceAccount:
  create: true
  name: "minio-sa"

metrics:
  serviceMonitor:
    enabled: false
    includeNode: false
    public: true
    additionalLabels: {}
    annotations: {}
    relabelConfigs: {}
    relabelConfigsCluster: {}
    namespace: ~
    interval: ~
    scrapeTimeout: ~

etcd:
  endpoints: []
  pathPrefix: ""
  corednsPathPrefix: ""
  clientCert: ""
  clientCertKey: ""