global:
  redis:
    password: <path:home-k8s/data/redis/oauth2-proxy/root#password>
  storageClass: "ceph-block"

nameOverride: "redis-oauth2-proxy"
fullnameOverride: "redis-oauth2-proxy"
namespaceOverride: "redis-system"

master:
  nodeSelector:
    node-type: worker
  podAffinityPreset: "soft"
  resourcesPreset: "small"

replica:
  replicaCount: 2
  nodeSelector:
    node-type: worker
  podAffinityPreset: "soft"
  resourcesPreset: "small"

volumePermissions:
  enabled: true

auth:
  enabled: true
  sentinel: false