apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist
  interfaces:
  - ^.*
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  blocks:
  - cidr: "192.168.123.105/32" # ex) 192.168.100.0/30
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
