apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: blog-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: www.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: rookceph-ingress
  namespace: rook-ceph
spec:
  ingressClassName: nginx
  rules:
  - host: storage.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 7000
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://proxy.choigonyok.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://proxy.choigonyok.com/oauth2/start?rd=$escaped_request_uri"
  name: network-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: network.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: hubble-ui
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: mimir-ingress
  namespace: metric-system
spec:
  ingressClassName: nginx
  rules:
  - host: mimir.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: app-mimir-distributor-headless
            port:
              number: 8080
        path: /distributor/ha_tracker
        pathType: Prefix