apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: blog-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: www.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: nginx-service
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: rookceph-ingress
  namespace: rook-ceph
spec:
  ingressClassName: nginx
  rules:
  - host: storage.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 7000
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-ingress
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: network.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: hubble-ui
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: mimir-ingress
  namespace: metric-system
spec:
  ingressClassName: nginx
  rules:
  - host: mimir.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: app-mimir-distributor-headless
            port:
              number: 8080
        path: /distributor/ha_tracker
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: vault-ingress
  namespace: vault-system
spec:
  ingressClassName: nginx
  rules:
  - host: vault.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: vault-ui
            port:
              number: 8200
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techlog-ui-ingress
  namespace: dev-system
spec:
  ingressClassName: nginx
  rules:
  - host: www.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: techlog-ui
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: postgres-system
spec:
  ingressClassName: nginx
  rules:
  - host: postgres.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: app-zalando-operators-postgres-operator-ui
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimir-ingress
  namespace: metric-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /alertmanager
spec:
  ingressClassName: nginx
  rules:
  - host: alert.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: app-mimir-alertmanager
            port:
              number: 8080
        path: /
        pathType: Exact
  - host: alert.choigonyok.com
    http:
      paths:
      - backend:
          service:
            name: app-mimir-alertmanager
            port:
              number: 8080
        path: /alertmanager
        pathType: Exact
---