redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  rbac:
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - watch
      - list
      resourceNames:
      - avp-secret
  replicas: 2
  initContainers:
    - name: download-tools
      image: alpine/curl
      env:
        - name: AVP_VERSION
          value: 1.16.1
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  extraContainers:
    - name: avp-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.7.4
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp-helm.yaml
          name: cmp-plugin
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
    - name: avp
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.7.4
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin

  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
    - name: tmp-dir
      emptyDir: {}

applicationSet:
  replicas: 2

global:
  domain: cd.choigonyok.com
  logging:
    format: text
    level: debug

  affinity:
    podAntiAffinity: soft

  nodeSelector:
    node-type: worker
    
configs:
  params:
    server.insecure: true
  cm:
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - '*'
    oidc.config: |
      name: Keycloak
      issuer: https://auth.choigonyok.com/realms/home-k8s
      clientID: argocd-client
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ['openid', 'profile', 'email', 'groups']
    rbacConfig:
      policy.default: role:readonly
      policy.csv: |
        g, argocd-admin, role:admin
server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: {}
    extraTls: []