# https://www.keycloak.org/operator/basic-deployment
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: auth-system
spec:
  hostname:
    hostname: https://auth.choigonyok.com
    strict: false
    backchannelDynamic: true
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "1"
      memory: "1024M"
  db:
    vendor: postgres
    url: jdbc:postgresql://keycloak-pg.postgres-system.svc.cluster.local/keycloak_db
    poolMinSize: 30 
    poolInitialSize: 30
    poolMaxSize: 30
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  image: quay.io/keycloak/keycloak:25.0
  startOptimized: false 
  features:
    enabled:
      - multi-site 
      - authorization
      - docker
  transaction:
    xaEnabled: false 
  additionalOptions:
    - name: http-max-queued-requests
      value: "1000"
    - name: log-console-output
      value: json
    - name: metrics-enabled 
      value: 'true'
    - name: http-pool-max-threads 
      value: "66"
  ingress:
    enabled: false
  http:
    tlsSecret: example-tls-secret
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
  instances: 3
