global:
  redis:
    password: <path:home-k8s/data/redis/config/rootPassword>
  storageClass: "ceph-block"

namespaceOverride: "redis-system"

replica:
  replicaCount: 3
  nodeSelector:
    node-type: worker
  podAffinityPreset: "soft"

sentinel:
  enabled: true