# SecretStore는 외부 Vault 서버의 특정 경로에 저장된 시크릿들과, ExternalSecret을 연결해주는 컴포넌트입니다.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vault-system
spec:
  provider:
    vault:
      server: "vault-internal.vault-system.svc.cluster.local" # 수정, External Vault Server Host
      path: "k8s"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          key: "token"
---
# 외부 Vault 서버와 연결하기 위해 Vault Authn Token을 제공하는 오브젝트입니다.
apiVersion: v1
kind: Secret
metadata:
  name: vault-root-token
  namespace: vault-system
data:
  token: BASE64_ENCODED_VAULT_ROOT_TOKEN # Vault Root Token을 base64 인코딩한 값
---
# ExternalSecret은 SecretStore를 통해 Vault 시크릿들을 가져와서 K8s에 Secret 오브젝트로 저장하는 역할을 합니다.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-secret-minio
  namespace: vault-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: rootpassword # K8s에 저장될 시크릿의 키
    remoteRef:
      # ex) vault kv put kv/hello target=world
      key: data/minio/users # SecretEngine의 SubPath 
      property: rootpassword  # Vault에 저장된 시크릿의 키