apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-zalando
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  destination:
    name: ''
    namespace: postgres-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: zalando/manifests/clusters/grafana
      targetRevision: HEAD
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: zalando/manifests/clusters/keycloak
      targetRevision: HEAD
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: zalando/manifests/clusters/harbor
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true