nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local
image:
  repository: quay.io/minio/minio
  tag: RELEASE.2024-04-18T19-09-19Z
  pullPolicy: IfNotPresent

imagePullSecrets: []

mcImage:
  repository: quay.io/minio/mc
  tag: RELEASE.2024-04-18T16-45-29Z
  pullPolicy: IfNotPresent

mode: distributed

additionalLabels: {}
additionalAnnotations: {}
ignoreChartChecksums: false
extraArgs: []
# example for enabling FTP:
#   - --ftp=\"address=:8021\"
#   - --ftp=\"passive-port-range=10000-10010\"

extraVolumes: []
extraVolumeMounts: []
extraContainers: []

minioAPIPort: "9000"
minioConsolePort: "9001"

deploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

statefulSetUpdate:
  updateStrategy: RollingUpdate

priorityClassName: ""
runtimeClassName: ""
rootUser: ""
rootPassword: ""
existingSecret: "minio-vault-secret"

certsPath: "/etc/minio/certs/"
configPathmc: "/etc/minio/mc/"

mountPath: "/export"
bucketRoot: ""

drivesPerNode: 1
replicas: 3
pools: 1

tls:
  enabled: false
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key

trustedCertsSecret: ""

persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  storageClass: "ceph-block"
  volumeName: ""
  accessMode: ReadWriteOnce
  size: 250Gi

  subPath: ""

service:
  type: ClusterIP
  clusterIP: ~
  port: "9000"
  nodePort: 32000
  loadBalancerIP: ~
  externalIPs: []
  annotations: {}

  loadBalancerSourceRanges: []
  externalTrafficPolicy: Cluster

ingress:
  enabled: false
  ingressClassName: ~
  labels: {}
  annotations: {}
  path: /
  hosts: []
  tls: []

consoleService:
  type: ClusterIP
  clusterIP: ~
  port: "9001"
  nodePort: 32001
  loadBalancerIP: ~
  externalIPs: []
  annotations: {}
  loadBalancerSourceRanges: []

  externalTrafficPolicy: Cluster

consoleIngress:
  enabled: true
  ingressClassName: cilium
  labels: {}
  annotations:
    ingress.cilium.io/loadbalancer-mode: shared
    ingress.cilium.io/service-type: ClusterIP
  path: /
  hosts:
    - s3.choigonyok.com
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"
  readOnlyRootFilesystem: false

podAnnotations: {}
podLabels: {}
resources:
  requests:
    memory: 2Gi

policies: []

makePolicyJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

users:
  - accessKey: admin
    existingSecret: minio-vault-secret
    existingSecretKey: rootPassword
    policy: consoleAdmin

makeUserJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

svcaccts: []

makeServiceAccountJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

buckets:
  - name: test
    policy: none
    purge: false
    versioning: true
    objectlocking: false

makeBucketJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

customCommands:
customCommandJob:
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
  resources:
    requests:
      memory: 128Mi
  exitCommand: ""

postJob:
  podAnnotations: {}
  annotations: {}
  securityContext:
    enabled: false
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  nodeSelector: {}
  tolerations: []
  affinity: {}

environment:
  MINIO_REGION: "ap-northeast-2"

extraSecret: ~

oidc:
  enabled: false
  configUrl: "https://identity-provider-url/.well-known/openid-configuration"
  clientId: "minio"
  clientSecret: ""
  # Provide existing client secret from the Kubernetes Secret resource, existing secret will have priority over `clientId` and/or `clientSecret``
  existingClientSecretName: ""
  existingClientIdKey: ""
  existingClientSecretKey: ""
  claimName: "policy"
  scopes: "openid,profile,email"
  redirectUri: "https://console-endpoint-url/oauth_callback"
  # Can leave empty
  claimPrefix: ""
  comment: ""
  displayName: ""

networkPolicy:
  enabled: false
  flavor: cilium
  allowExternal: true
  egressEntities:
   - kube-apiserver

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1

serviceAccount:
  create: true
  name: "minio-sa"

metrics:
  serviceMonitor:
    enabled: true
    includeNode: false
    public: true
    additionalLabels: {}
    annotations: {}
    relabelConfigs: {}
    relabelConfigsCluster: {}
    namespace: ~
    interval: ~
    scrapeTimeout: ~

etcd:
  endpoints: []
  pathPrefix: ""
  corednsPathPrefix: ""
  clientCert: ""
  clientCertKey: ""