namespaceOverride: "oauth-system"

config:
  annotations: {}
  clientID: "oauth2-proxy-oauth"
  clientSecret: "x9Jb4KNWf3sRvMkUNwSCqykv3SBg9EBz"
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "TkFlc29DN094K2U2alFkb2hibWJNSE82T2hlMC9JUkg="
  cookieName: ""

extraArgs:
  - --provider=keycloak-oidc
  - --client-id=oauth2-proxy-oauth
  - --client-secret=x9Jb4KNWf3sRvMkUNwSCqykv3SBg9EBz
  - --redirect-url=https://proxy.choigonyok.com/oauth2/callback
  - --oidc-issuer-url=https://auth.choigonyok.com/realms/home-k8s
  - --allowed-role=oauth2-proxy-oauth:network-admin
  - --code-challenge-method=S256
  - --email-domain="*"
  - --whitelist-domain="*.choigonyok.com"
  - --insecure-oidc-allow-unverified-email

initContainers:
  waitForRedis:
    enabled: true
    image:
      repository: "alpine"
      tag: "latest"
      pullPolicy: "IfNotPresent"
    kubectlVersion: ""
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
    timeout: 180
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 300Mi
      # requests:
      #   cpu: 100m
      #   memory: 300Mi


metrics:
  enabled: false

sessionStorage:
  # Can be one of the supported session storage cookie|redis
  type: redis
  redis:
    password: <path:home-k8s/data/redis/oauth2-proxy/root#password>
    clientType: "sentinel"
    sentinel:
      existingSecret: ""
      password: <path:home-k8s/data/redis/oauth2-proxy/root#password>
      masterName: "oauth2-proxy-master"
      connectionUrls: [redis://redis-oauth2-proxy-node-0.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379, redis://redis-oauth2-proxy-node-1.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379, redis://redis-oauth2-proxy-node-2.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379]

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
  hosts:
    - proxy.choigonyok.com
  labels: {}
  annotations: {}
  # tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local