namespaceOverride: "oauth-system"
replicaCount: 3

nodeSelector:
  node-type: worker

config:
  configFile: ""
  annotations: {}
  clientID: "oauth2-proxy-client"
  clientSecret: <path:kv/data/oauth2-proxy#CLIENT_SECRET>
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: <path:kv/data/oauth2-proxy#COOKIE_SECRET>
  cookieName: ""
  google: {}

extraArgs:
  - --provider=keycloak-oidc
  - --client-id=oauth2-proxy-client
  - --client-secret=<path:kv/data/key-cloak#OAUTH2_PROXY_CLIENT_SECRET>
  - --redirect-url=https://proxy.choigonyok.com/oauth2/callback
  - --oidc-issuer-url=https://auth.choigonyok.com/realms/home-k8s
  - --code-challenge-method=S256
  - --email-domain="*"
  - --whitelist-domain="*.choigonyok.com"
  - --insecure-oidc-allow-unverified-email
  - --cookie-secure=false
  - --allowed-role=viewer
  - --allowed-group=testers
  - --skip-provider-button=true
  - --ssl-insecure-skip-verify
  - --scope=openid profile
  - --cookie-domain=".choigonyok.com"

initContainers:
  waitForRedis:
    enabled: true
    image:
      repository: "alpine"
      tag: "latest"
      pullPolicy: "IfNotPresent"
    kubectlVersion: ""
    securityContext:
      enabled: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
    timeout: 180
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 300Mi
      # requests:
      #   cpu: 100m
      #   memory: 300Mi

deploymentAnnotations: {}
podAnnotations: {}
htpasswdFile:
  enabled: false
alphaConfig:
  enabled: false
authenticatedEmailsFile:
  enabled: false

metrics:
  enabled: false

sessionStorage:
  type: redis
  redis:
    existingSecret: ""
    passwordKey: "redis-password"
    password: <path:kv/data/oauth2-proxy#REDIS_PASSWORD>
    clientType: "sentinel"
    cluster:
      connectionUrls: []
    sentinel:
      passwordKey: "redis-sentinel-password"
      existingSecret: ""
      password: <path:kv/data/oauth2-proxy#REDIS_PASSWORD>
      masterName: "oauth2-proxy-master"
      connectionUrls: "redis://redis-oauth2-proxy-node-0.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379,redis://redis-oauth2-proxy-node-1.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379,redis://redis-oauth2-proxy-node-2.redis-oauth2-proxy-headless.redis-system.svc.cluster.local:26379"

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
  hosts:
    - proxy.choigonyok.com
  labels: {}
  annotations: {}

redis:
  enabled: true
  redisPort: 6379
  global:
    redis:
      password: <path:kv/data/oauth2-proxy#REDIS_PASSWORD>
    storageClass: "ceph-block"

  nameOverride: "redis-oauth2-proxy"
  fullnameOverride: "redis-oauth2-proxy"
  namespaceOverride: "redis-system"

  replica:
    replicaCount: 3
    nodeSelector:
      node-type: worker
    podAffinityPreset: "soft"
    resourcesPreset: "small"
    
  sentinel:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/redis-sentinel
      tag: 7.2.5-debian-12-r0
      digest: ""
      debug: false
    resourcesPreset: "small"
    masterSet: "oauth2-proxy-master"

  volumePermissions:
    enabled: true

  auth:
    enabled: true
    sentinel: false