apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: blog-issuer
  namespace: dev-system
spec:
  acme:
    email: "achoistic98@naver.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: blog-tls
    solvers:
    - http01:
        ingress:
          class: nginx
