apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: postgres-issuer
  namespace: postgres-system
spec:
  acme:
    email: "achoistic98@naver.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: postgres-tls
    solvers:
    - http01:
        ingress:
          class: cilium
