apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-policy
  namespace: vault-system
data:
  minio.hcl: |
    path "home-k8s/data/minio/*" {
      capabilities = ["read", "list"]
    }
  mon.hcl: |
    path "home-k8s/data/mon/*" {
      capabilities = ["read", "list"]
    }
  mon.hcl: |
    path "pki/issue/consul-server" {
      capabilities = ["create", "update"]
    }    