apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-external-secrets-secrets
  namespace: argocd-system
spec:
  destination:
    name: ''
    namespace: vault-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: external-secrets/manifests/secrets/keycloak
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true