apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-loki
  namespace: argocd-system
spec:
  destination:
    name: ''
    namespace: monitor-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: 'https://github.com/choigonyok/home-k8s.git'
      path: loki/loki
      targetRevision: HEAD
      plugin:
        name: argocd-vault-plugin-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true